events {}

http {
  upstream ridefleet_backend {
    server grupo-a-api-1:3000;
    server grupo-a-api-2:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://ridefleet_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}